# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


class fibonacci_sequence:
    def __init__(self, fib_start, fib_one, fib_two, end_point):
        self.fib_start = fib_start
        self.fib_one = fib_one
        self.fib_two = fib_two
        self.end_point = end_point

    def fibonacci_builder(self):
        result = 0

        while self.fib_start < self.end_point:
            self.fib_start = (self.fib_one + self.fib_two)
            if self.fib_start % 2 == 0:
                result = result + self.fib_start
            self.fib_one = self.fib_two
            self.fib_two = self.fib_start

        return result


fib = fibonacci_sequence(0, 1, 1, 4000000)

print(fib.fibonacci_builder())
